
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nooalqkkbkrrbsrqnaqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vb2FscWtrYmtycmJzcnFuYXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTI0ODEsImV4cCI6MjA2MTcyODQ4MX0.zTtpRsUQ8PTA9fVjIpJDYce1A3h1e-UnTCOdL1vqyKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
